
import __ASTRO_IMAGE_IMPORT_1x8Cut from "@/assets/background.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.mdx";
import __ASTRO_IMAGE_IMPORT_18zSQ8 from "@/assets/astro.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.mdx";
import __ASTRO_IMAGE_IMPORT_2lyrPY from "../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fdarius-clark.mdx";
import __ASTRO_IMAGE_IMPORT_ZIUG1I from "../../assets/arold.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Farold-norelus.mdx";
import __ASTRO_IMAGE_IMPORT_2fBOp8 from "../../assets/RichardFaria.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Frichard-faria.mdx";
import __ASTRO_IMAGE_IMPORT_Z2ptOsV from "../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fkenn-faria.mdx";
import __ASTRO_IMAGE_IMPORT_Zsw88X from "../../assets/Anthony.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fanthony-gonzales.mdx";
import __ASTRO_IMAGE_IMPORT_s0yHl from "../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Ftarun-kumar.mdx";
import __ASTRO_IMAGE_IMPORT_Z1ySCus from "@/assets/projects/CBC.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcertified-bag-chasers-light.mdx";
import __ASTRO_IMAGE_IMPORT_GoSf7 from "@/assets/projects/pronto-junk-removal.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpronto-junk-removal.mdx";
import __ASTRO_IMAGE_IMPORT_Z35uLh from "@/assets/projects/pablos-peak-roofing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpablos-peak-roofing.mdx";
import __ASTRO_IMAGE_IMPORT_mdiV4 from "@/assets/projects/roonys-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Froonys-marketing.mdx";
import __ASTRO_IMAGE_IMPORT_PtM3S from "@/assets/projects/tsf.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftok-secret-formula.mdx";
import __ASTRO_IMAGE_IMPORT_Z1tjGKR from "@/assets/projects/farias-demolition.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffarias-demolition.mdx";
import __ASTRO_IMAGE_IMPORT_daKB6 from "../../assets/projects/universalchillers.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Funiversal-chillers.mdx";
export default new Map([["@/assets/background.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.mdx", __ASTRO_IMAGE_IMPORT_1x8Cut], ["@/assets/astro.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ffirst-post.mdx", __ASTRO_IMAGE_IMPORT_18zSQ8], ["../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fdarius-clark.mdx", __ASTRO_IMAGE_IMPORT_2lyrPY], ["../../assets/arold.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Farold-norelus.mdx", __ASTRO_IMAGE_IMPORT_ZIUG1I], ["../../assets/RichardFaria.png?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Frichard-faria.mdx", __ASTRO_IMAGE_IMPORT_2fBOp8], ["../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fkenn-faria.mdx", __ASTRO_IMAGE_IMPORT_Z2ptOsV], ["../../assets/Anthony.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Fanthony-gonzales.mdx", __ASTRO_IMAGE_IMPORT_Zsw88X], ["../../assets/placeholder.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftestimonials%2Ftarun-kumar.mdx", __ASTRO_IMAGE_IMPORT_s0yHl], ["@/assets/projects/CBC.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcertified-bag-chasers-light.mdx", __ASTRO_IMAGE_IMPORT_Z1ySCus], ["@/assets/projects/pronto-junk-removal.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpronto-junk-removal.mdx", __ASTRO_IMAGE_IMPORT_GoSf7], ["@/assets/projects/pablos-peak-roofing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpablos-peak-roofing.mdx", __ASTRO_IMAGE_IMPORT_Z35uLh], ["@/assets/projects/roonys-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Froonys-marketing.mdx", __ASTRO_IMAGE_IMPORT_mdiV4], ["@/assets/projects/tsf.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ftok-secret-formula.mdx", __ASTRO_IMAGE_IMPORT_PtM3S], ["@/assets/projects/farias-demolition.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffarias-demolition.mdx", __ASTRO_IMAGE_IMPORT_Z1tjGKR], ["../../assets/projects/universalchillers.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Funiversal-chillers.mdx", __ASTRO_IMAGE_IMPORT_daKB6]]);
		